### ISSUE TITLE
add wine-lol script to path

### ISSUE THREAD

**Issue by saltedcoffii** [M-Reimer/wine-lol#106]
The PATH to the wine-lol executable, on arch linux via the AUR at least, is cumbersome to access, and shares the same prefix with the system wine, which can cause problems if they are too far different. Have you considered adding a script such as 
```
#!/usr/bin/env sh
winelolprefix=${WINEPREFIX:-"${HOME}/.wine-lol"}
env WINEPREFIX="${winelolprefix}" /opt/wine-lol/bin/wine "${@}"
```
to the PATH, such as at `/usr/bin/wine-lol`

**Comment by DanRiffo** [comment]
I do not agree with this. When you use an alternative wine you have to be responsible about your own wineprefixes. No need for the maintainer to add clutter/bloat with a mostly useless script.
Just my two cents.

**Comment by M-Reimer** [comment]
Most users use helpers or scripts anyway. And it is not my job to "standardize" where the LoL wine prefix should be. It could be in a number of different locations depending on which guide or helper you use.

**Comment by saltedcoffii** [comment]
I understand your point, and it does make sense from a technical perspective. However, many users may not have an intricate understanding of how to use wine and want something that "just works." Having a script as such may increase ease of use for users that run Linux and just want to play League without having to configure or understand wine prefixes. If my script doesn't match the needs of the project or the needs of the majority of nontechnical users, maybe another solution would be better, such as adding working instructions to the README explaining how to set up a helper to use wine-lol. I use bottles, for example.

**Comment by M-Reimer** [comment]
The "solution" for the "non-technical" users is https://aur.archlinux.org/packages/leagueoflegends-git
And the "really non-technical user" probably doesn't need all of this and will use Lutris anyway.

**Comment by M-Reimer** [comment]
Added some note to the README.md file which now points to leagueoflegends-git, too.

I only want to do basic maintenance and no longer want to spend too much time into wine-lol. Currently, I'm quite happy that all it does is build or repackage the wine version provided by GloriousEggroll. If I add some script, then people will come with all kinds of feature requests that I do not want to deal with.

I no longer play LoL AT ALL since many years and I'm not planning to get back into it. All I still try to do is support the Linux Gaming community a bit. I do not use wine-lol by myself!
