### ISSUE TITLE
Game Client crashes on 9.20

### ISSUE THREAD

**Issue by jukefr** [M-Reimer/wine-lol#30]
With the new patch of League 9.20 and the latest wine-lol 4.17x the launcher works somewhat fine although it seems quite slow to launch but the client crashes whenever a game is started.

Here are the 3 relevant log lines I get from wine whenever I start a game and it crashes :
```
00b5:fixme:ntdll:NtCreatePowerRequest (0x32e914, 0x32e918): stub
01c2:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
01c2:fixme:ntdll:NtQuerySystemInformation SystemExtendedProcessInformation, len 1048576, buffer 0x3530020, stub!
```

**Comment by LuisMichaelis** [comment]
Can confirm. I have no backtrace sadly but [here](https://pastebin.com/uYFefwRD) is the wine log. The crash happens at line 1677.

**Comment by aleex5** [comment]
apparently they made changes to the anticheat, we're screwed

**Comment by M-Reimer** [comment]
Please discuss anything about this in this subreddit thread:
https://www.reddit.com/r/leagueoflinux/comments/dfdik3/crashing_ingame_on_patch_920_a_critical_error_has/

You may also follow this Wine bug about this:
https://bugs.winehq.org/show_bug.cgi?id=47915
Please only follow it by adding yourself to the CC list. The comments are for development related discussion only. The bug is really easy to reproduce by developers so no need for additional console dumps or crash dumps.

I'll lock the discussion here as this GitHub project is for maintaining the PKGBUILD's only. I'm no wine developer so I can't fix such bugs in wine itself.
