### ISSUE TITLE
64bit version for Legends of Runeterra

### ISSUE THREAD

**Issue by Araly** [M-Reimer/wine-lol#35]
Do you think you could have a 64bit version of wine-lol to use with Legends of Runeterra ?

The game displays the same difficulties that League of Legends does (critical error on game launch), so I tried using wine-lol with it, but it's a 64bit game, and wine-lol is 32bit only (if I'm not mistaking).

If it doesn't make sense to make a 64bit version as its not related to League of Legends, what would I need to change in a fork to make it 64bit ?

Thank you

**Comment by M-Reimer** [comment]
The issue, that is fixed with wine-lol, doesn't exist in 64 bit wine.

Just have a closer look at the primary patch applied here:
https://bugs.winehq.org/attachment.cgi?id=64481
> // FIXME All of this code is i386 Linux-specific. It may want to live in
> //       signal_i386.c.

So building with 64 bit will not help. It has to be some other issue. Hopefully one where the fix can go into standard wine-staging so no "special wine" is needed.

**Comment by Araly** [comment]
hum, I see.

would the new crash dump help ? I'll upload it here, but where should I post for this new issue then, in bugs.winehq.org ?

well apparently github doesn't support the .tmp filetype and denies me from uploading it

**Comment by M-Reimer** [comment]
Only the wine guys can help you. This issue is off topic in this GitHub repo and even if it would be related to LoL: I can never fix bugs in wine as I miss the knowledge to do so.
