### ISSUE TITLE
Any guide, or plans to make a wiki?

### ISSUE THREAD

**Issue by Klairm** [M-Reimer/wine-lol#48]
Sorry for this question, but I already compiled and built everything ,but don't know what to do next, and I don't find any guide.

Any suggestion?

**Comment by M-Reimer** [comment]
I would say "just install LoL now" :stuck_out_tongue: 

I had this one here prepared for everyone who does not want to use Lutris for installation. I initially installed my LoL setup with this but, so far, never had to reinstall and according to some feedback there may be some fixes needed to make this install LoL with the new client properly:

https://github.com/M-Reimer/leagueoflegends-linux

I can assist if there are questions, but tbh I haven't started LoL for several weeks. I only play whenever I have to (because my friends want to play). IMHO this is one of the worst games on earth.

**Comment by Klairm** [comment]
> I would say "just install LoL now" 
> 
> I had this one here prepared for everyone who does not want to use Lutris for installation. I initially installed my LoL setup with this but, so far, never had to reinstall and according to some feedback there may be some fixes needed to make this install LoL with the new client properly:
> 
> https://github.com/M-Reimer/leagueoflegends-linux
> 
> I can assist if there are questions, but tbh I haven't started LoL for several weeks. I only play whenever I have to (because my friends want to play). IMHO this is one of the worst games on earth.

With that installer got it working, thought i had to edit the script for download the EUW version instead of NA, also the Client seems  little glitchy like some buttons are black and can't see chat, but can play perfectly, thanks!
