### ISSUE TITLE
Artificial client launch delay possibly unnecessary on Wine 6.23 (?)

### ISSUE THREAD

**Issue by Hubro** [M-Reimer/wine-lol#97]
A recent comment on [this bug report](https://bugs.winehq.org/show_bug.cgi?id=50868) suggests that the client launches properly without the artificial 2-3 minute delay on Wine 6.23.

I don't personally have the know-how to try building wine-lol with Wine 6.23, I just use the pre-compiled binaries, but I thought I'd let you know in case you want to test it out. It would be a huge quality of life upgrade for League gamers.

**Comment by M-Reimer** [comment]
Let me quote from the README.md of this project:

> I have no time to test new versions. So it's you who has to do this! This means that a new version can not be requested at all in an Issue but only with a Pull Request!

It's not just a "smash a new version number in there and recompile" job but the patch, that makes actually run LoL in Wine is not compatible with anything beyond the version I use here.

And before that question pops up again: There are two patches out there that make Wine compatible with LoL. The ony which requires abi.vsyscall32=0 to be in place and the one I use which requires a patched glibc.

The patch which requires the global setting change still receives some "love" from developers that keep it somewhat updated with more recent versions of Wine while I could not manage to get anyone to update the glibc based patch because some people think it is too difficult to use. https://www.reddit.com/r/leagueoflinux/comments/pb4wqy/did_the_upgrade_to_cef91_as_part_of_1117_break/har1djw/?context=3
